# This file is automatically generated when installing rpy2
# For permanent changes, edit __init__py.in in the source directory.

import os
os.environ["R_HOME"]="/usr/local/packages/R-2.7/lib/R"

from rinterface import *
